### ISSUE TITLE
NoSuchMethodError 

### ISSUE THREAD

**Issue by JunkyBulgaria** [Shevchik/ProtocolSupport#37]
Am i the only one recieveing this error? Today's spigot built 10h ago.
```[21:15:55] [Server thread/INFO]: [ProtocolSupport] Loading ProtocolSupport v4.19
[21:15:55] [Server thread/WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_8_R3.MinecraftServer.getServerConnection()Lnet/minecraft/server/v1_8_R3/ServerConnection;
[21:15:55] [Server thread/WARN]: 	at protocolsupport.injector.NettyInjector.inject(NettyInjector.java:19)
[21:15:55] [Server thread/WARN]: 	at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:16)
[21:15:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:296)
[21:15:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
[21:15:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524)
[21:15:55] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:15:55] [Server thread/INFO]: [ProtocolSupport] Enabling ProtocolSupport v4.19```

**Comment by Shevchik** [comment]
Are you sure that you are running unmodified spigot? CraftBukkit won't work, it doesn't have this method and many more actually.

**Comment by JunkyBulgaria** [comment]
Nope, last revision from BuildTools and i haven't touched anything in it.
http://92.222.126.78/spigot.jar

**Comment by Shevchik** [comment]
Your build is totally corrupted you craftbukkit package is v1.8.3.v1.8.3, that shouldn't be like that.

**Comment by JunkyBulgaria** [comment]
Latest, just downloaded it from their site.

**Comment by Shevchik** [comment]
I just built spigot with latest buildtools and everything is fine. Try cleaning up your build workspace, it is totally something wrong on your end

**Comment by JunkyBulgaria** [comment]
Alright, sorry for wasting your time. If this still exists i'll re-open the issue.
