### ISSUE TITLE
1.7.X Version client cant use Uskyblock Server

### ISSUE THREAD

**Issue by swab201** [Shevchik/ProtocolSupport#41]
Hello i m using Uskyblock v2.3-HF7i version. i use Protocolsupport #178 build is all is ok. But i update to #184 build. 1.7.X client user try to go island. they are crash. here is the PS debug log
ah, and i use ProtocolsupportBungee Too. BungeeServer and Spigot Server all Lastest Build (spigot 1.8.8)

[13:16:11] [Server thread/INFO]: swan201 issued server command: /is
[13:16:13] [Netty Server IO #0/WARN]: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:16:13] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:280)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:16:13] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:16:13] [Netty Server IO #0/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[13:16:13] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[13:16:13] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:543)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[13:16:13] [Netty Server IO #0/WARN]: 	... 20 more
[13:16:13] [Netty Server IO #0/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): PooledUnsafeDirectByteBuf(ridx: 0, widx: 0, cap: 256)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:570)
[13:16:13] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.PacketDataSerializer.readByte(PacketDataSerializer.java:515)
[13:16:13] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:36)
[13:16:13] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_7.serverboundtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:164)
[13:16:13] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_7.serverboundtransformer.PacketDecoder.decode(PacketDecoder.java:53)
[13:16:13] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedDecoder.decode(WrappedDecoder.java:27)
[13:16:13] [Netty Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
[13:16:13] [Netty Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:16:13] [Netty Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:16:13] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[13:16:13] [Netty Server IO #0/WARN]: 	... 22 more
[13:16:13] [Netty Server IO #0/WARN]: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:205)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:16:13] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:16:13] [Netty Server IO #0/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[13:16:13] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[13:16:13] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:543)
[13:16:13] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[13:16:13] [Netty Server IO #0/WARN]: 	... 19 more
[13:16:13] [Netty Server IO #0/WARN]: Caused by: java.io.IOException: Packet 0/1 (PacketPlayInChat) was larger than expected, found 191 bytes extra whilst reading packet 1
[13:16:13] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_7.serverboundtransformer.PacketDecoder.decode(PacketDecoder.java:58)
[13:16:13] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedDecoder.decode(WrappedDecoder.java:27)
[13:16:13] [Netty Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
[13:16:13] [Netty Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:16:13] [Netty Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:16:13] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[13:16:13] [Netty Server IO #0/WARN]: 	... 21 more
[13:16:13] [Server thread/INFO]: swan201 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.

sorry for my bad english

**Comment by Shevchik** [comment]
Should be fixed try latest build.

**Comment by swab201** [comment]
Thank you!
