### ISSUE TITLE
1.5.2, 1.7.X Client have problem

### ISSUE THREAD

**Issue by swan201** [Shevchik/ProtocolSupport#44]
1.5.2 crash ranbomly and 1.7.X User go some location they are kick to server a java error masage. I dont know This is Spigot Bug or Protocolsupport bug. But 1.8 higher Client is all ok. 

Im enable PS debug. But console only show client java error masage. How do you think about this errors.

This issue is, I update to spigot 1.8.8 and 8/2 protocolsupport

**Comment by Shevchik** [comment]
I need your server address so i can join and debug that

**Comment by swab201** [comment]
address is phgmy.ptcs.kr 

This is Bungee Server. In to a lobby than come to Wild plz (not Skyblock)

**Comment by Shevchik** [comment]
Okay, i probably found the problem, i will tell you when i fix it.

**Comment by swan201** [comment]
Thank you. :)

**Comment by Shevchik** [comment]
Okay, try new build.
Maybe it won't fix the problem, but at least it should show more info in case the exception will occure again (don't forget to enable the debug using /ps debug command).

**Comment by swan201** [comment]
I update Plugins And on Debug option. But stil consle show only java.lang.NegativeArraySizeException.

And Client error is Internal Exception: io.netty.handler.codec.DecorderException: Java.lang.IndexOutofBoundsException: readerIndex(14) + length(4) exceeds writerIndex(14): UnpooledHeapByteBuf(ridx:14 widx: 14, cap:14)

**Comment by Shevchik** [comment]
Try again, let's hope it will catch exception this time

**Comment by swan201** [comment]
good now Plugin catch the exception.

[05:30:42] [Netty Server IO #1/WARN]: java.lang.NegativeArraySizeException
[05:30:42] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.PacketDataSerializer.a(PacketDataSerializer.java:223)
[05:30:42] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.PacketDataSerializer.readArray(PacketDataSerializer.java:277)
[05:30:42] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.transformer.v_1_7.clientboundtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:454)
[05:30:42] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.transformer.v_1_7.clientboundtransformer.PacketEncoder.encode(PacketEncoder.java:61)
[05:30:42] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:30)
[05:30:42] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:13)
[05:30:42] [Netty Server IO #1/WARN]: 	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
[05:30:42] [Netty Server IO #1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[05:30:42] [Netty Server IO #1/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[05:30:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[05:30:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:506)
[05:30:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:264)
[05:30:42] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[05:30:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:270)
[05:30:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[05:30:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[05:30:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[05:30:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[05:30:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[05:30:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[05:30:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[05:30:42] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[05:30:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6$3.run(NettyChannelInjector.java:361)
[05:30:42] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[05:30:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[05:30:42] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[05:30:42] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[05:30:42] [Netty Server IO #1/ERROR]: java.lang.NegativeArraySizeException
[05:30:43] [Netty Server IO #1/WARN]: java.io.IOException: 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다
[05:30:43] [Netty Server IO #1/WARN]: 	at sun.nio.ch.SocketDispatcher.read0(Native Method)
[05:30:43] [Netty Server IO #1/WARN]: 	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
[05:30:43] [Netty Server IO #1/WARN]: 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
[05:30:43] [Netty Server IO #1/WARN]: 	at sun.nio.ch.IOUtil.read(Unknown Source)
[05:30:43] [Netty Server IO #1/WARN]: 	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
[05:30:43] [Netty Server IO #1/WARN]: 	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
[05:30:43] [Netty Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
[05:30:43] [Netty Server IO #1/WARN]: 	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225)
[05:30:43] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
[05:30:43] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
[05:30:43] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
[05:30:43] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
[05:30:43] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
[05:30:43] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[05:30:43] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[05:30:43] [Server thread/INFO]: swan201 lost connection: Internal Exception: java.io.IOException: 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다

**Comment by Shevchik** [comment]
Try again, that will show if the error is really where i think it is.

**Comment by swan201** [comment]
[05:52:15] [Netty Server IO #1/WARN]: java.lang.RuntimeException: Too big array length of 61696
[05:52:15] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.PacketDataSerializer.a(PacketDataSerializer.java:236)
[05:52:15] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayOutMapChunk.b(PacketPlayOutMapChunk.java:39)
[05:52:15] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.transformer.v_1_7.clientboundtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:446)
[05:52:15] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.transformer.v_1_7.clientboundtransformer.PacketEncoder.encode(PacketEncoder.java:61)
[05:52:15] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:30)
[05:52:15] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:13)
[05:52:15] [Netty Server IO #1/WARN]: 	at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
[05:52:15] [Netty Server IO #1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[05:52:15] [Netty Server IO #1/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[05:52:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[05:52:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:506)
[05:52:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:264)
[05:52:15] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[05:52:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:270)
[05:52:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[05:52:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[05:52:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[05:52:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[05:52:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[05:52:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[05:52:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[05:52:15] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[05:52:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6$3.run(NettyChannelInjector.java:361)
[05:52:15] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[05:52:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[05:52:15] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[05:52:15] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)


Here is it. Now Not crash Just see this error again again and again

**Comment by Shevchik** [comment]
Well, that is enough, i know where the error is and how to fix it. I will notify you when i will fix it.

**Comment by swan201** [comment]
Thank you

**Comment by swan201** [comment]
Well. 1.5.2 Client is almost same issue i think. console Say Too big array. 

[06:03:48] [Netty Server IO #0/WARN]: java.lang.RuntimeException: Too big array length of 37120
[06:03:48] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.PacketDataSerializer.a(PacketDataSerializer.java:236)
[06:03:48] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayOutMapChunk.b(PacketPlayOutMapChunk.java:39)
[06:03:48] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:49)
[06:03:48] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PacketEncoder.encode(PacketEncoder.java:47)
[06:03:48] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:30)
[06:03:48] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:13)
[06:03:48] [Netty Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
[06:03:48] [Netty Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[06:03:48] [Netty Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[06:03:48] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[06:03:48] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:504)
[06:03:48] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:264)
[06:03:48] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[06:03:48] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:270)
[06:03:48] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[06:03:48] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[06:03:48] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[06:03:48] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[06:03:48] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[06:03:48] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[06:03:48] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[06:03:48] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[06:03:48] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6$3.run(NettyChannelInjector.java:359)
[06:03:48] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[06:03:48] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[06:03:48] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[06:03:48] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[06:03:48] [Netty Server IO #0/ERROR]: java.lang.RuntimeException: Too big array length of 37120

**Comment by Shevchik** [comment]
Try now, it should all be fixed

**Comment by swan201** [comment]
all is fine. Thanks !
