### ISSUE TITLE
1.7.X Client Crash Open The Chest

### ISSUE THREAD

**Issue by swan201** [Shevchik/ProtocolSupport#45]
I Use Protocolsupport today Version And Spigot 1.8.8 And Bungee Server

[10:04:15] [Netty Server IO #1/WARN]: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[10:04:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:280)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[10:04:15] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[10:04:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[10:04:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:541)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[10:04:15] [Netty Server IO #1/WARN]: 	... 20 more
[10:04:15] [Netty Server IO #1/WARN]: Caused by: java.io.EOFException
[10:04:15] [Netty Server IO #1/WARN]: 	at java.io.DataInputStream.readUnsignedShort(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: 	at java.io.DataInputStream.readUTF(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: 	at java.io.DataInputStream.readUTF(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:80)
[10:04:15] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53)
[10:04:15] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.PacketDataSerializer.h(PacketDataSerializer.java:179)
[10:04:15] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.PacketDataSerializer.i(PacketDataSerializer.java:197)
[10:04:15] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:42)
[10:04:15] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.transformer.v_1_7.serverboundtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:166)
[10:04:15] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.transformer.v_1_7.serverboundtransformer.PacketDecoder.decode(PacketDecoder.java:53)
[10:04:15] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedDecoder.decode(WrappedDecoder.java:27)
[10:04:15] [Netty Server IO #1/WARN]: 	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[10:04:15] [Netty Server IO #1/WARN]: 	... 22 more
[10:04:15] [Netty Server IO #1/WARN]: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[10:04:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:280)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[10:04:15] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[10:04:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[10:04:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:541)
[10:04:15] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[10:04:15] [Netty Server IO #1/WARN]: 	... 20 more
[10:04:15] [Netty Server IO #1/WARN]: Caused by: java.io.EOFException
[10:04:15] [Netty Server IO #1/WARN]: 	at java.io.DataInputStream.readUnsignedShort(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: 	at java.io.DataInputStream.readUTF(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: 	at java.io.DataInputStream.readUTF(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:80)
[10:04:15] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53)
[10:04:15] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.PacketDataSerializer.h(PacketDataSerializer.java:179)
[10:04:15] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.PacketDataSerializer.i(PacketDataSerializer.java:197)
[10:04:15] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:42)
[10:04:15] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.transformer.v_1_7.serverboundtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:166)
[10:04:15] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.transformer.v_1_7.serverboundtransformer.PacketDecoder.decode(PacketDecoder.java:53)
[10:04:15] [Netty Server IO #1/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedDecoder.decode(WrappedDecoder.java:27)
[10:04:15] [Netty Server IO #1/WARN]: 	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[10:04:15] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[10:04:15] [Netty Server IO #1/WARN]: 	... 22 more
[10:04:15] [Server thread/INFO]: WonPat_5277 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.

**Comment by swan201** [comment]
I think 1.8.7 to 1.8.8 have many change Protocol Side

**Comment by Shevchik** [comment]
No, they did not, i just forgot 1 simple thing

**Comment by Shevchik** [comment]
Should be fixed now
