### ISSUE TITLE
1.5.2 /1.6.X Crash Some Location (like Dungun)

### ISSUE THREAD

**Issue by swan201** [Shevchik/ProtocolSupport#46]
1.7.X and 1.8.X Version is fine. Here is the PS debug LOG

[16:37:48] [Netty Server IO #1/WARN]: java.io.IOException: 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다
[16:37:48] [Netty Server IO #1/WARN]: 	at sun.nio.ch.SocketDispatcher.read0(Native Method)
[16:37:48] [Netty Server IO #1/WARN]: 	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
[16:37:48] [Netty Server IO #1/WARN]: 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
[16:37:48] [Netty Server IO #1/WARN]: 	at sun.nio.ch.IOUtil.read(Unknown Source)
[16:37:48] [Netty Server IO #1/WARN]: 	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
[16:37:48] [Netty Server IO #1/WARN]: 	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
[16:37:48] [Netty Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
[16:37:48] [Netty Server IO #1/WARN]: 	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225)
[16:37:48] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
[16:37:48] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
[16:37:48] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
[16:37:48] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
[16:37:48] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
[16:37:48] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:37:48] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:37:48] [Server thread/INFO]: swan201 lost connection: Internal Exception: java.io.IOException: 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다
[16:37:48] [Server thread/INFO]: swan201님이 니엘서버에서 퇴장하셨습니다.
[16:37:50] [Server thread/INFO]: Torcj_ issued server command: /창고
[16:37:57] [Server thread/INFO]: [[0;31;22m타멧[0;37;1m][m [m[0;33;22mD[0;37;1m [0;34;1mFa[0;37;1m [0;36;1mFi[0;37;1m [0;36;1m[유저][0;32;1m[0;36;1mBJtamet[m 혼자있고싶다고 나가라하는건[m
[16:38:02] [Server thread/INFO]: [[0;31;22m타멧[0;37;1m][m [m[0;33;22mD[0;37;1m [0;34;1mFa[0;37;1m [0;36;1mFi[0;37;1m [0;36;1m[유저][0;32;1m[0;36;1mBJtamet[m 친목이랑 관계없는디..[m
[16:38:02] [Netty Server IO #3/WARN]: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[16:38:02] [Netty Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:257)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[16:38:02] [Netty Server IO #3/WARN]: 	at protocolsupport.protocol.core.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:108)
[16:38:02] [Netty Server IO #3/WARN]: 	at protocolsupport.protocol.core.initial.Minecraft152PingResponseTask.run(Minecraft152PingResponseTask.java:19)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:123)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:38:02] [Netty Server IO #3/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:38:02] [Netty Server IO #3/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[16:38:02] [Netty Server IO #3/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[16:38:02] [Netty Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:520)
[16:38:02] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[16:38:02] [Netty Server IO #3/WARN]: 	... 17 more
[16:38:02] [Netty Server IO #3/WARN]: Caused by: java.io.IOException: Can't deserialize unknown packet 10
[16:38:02] [Netty Server IO #3/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.serverboundtransformer.PacketDecoder.decode(PacketDecoder.java:56)
[16:38:02] [Netty Server IO #3/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedDecoder.decode(WrappedDecoder.java:27)
[16:38:02] [Netty Server IO #3/WARN]: 	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
[16:38:02] [Netty Server IO #3/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:38:02] [Netty Server IO #3/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:38:02] [Netty Server IO #3/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[16:38:02] [Netty Server IO #3/WARN]: 	... 19 more

**Comment by Shevchik** [comment]
I'm currently unable to reproduce this, but it is definitely caused by some client action. Try findning out what is it exactly.

**Comment by swan201** [comment]
I dont now About that. Just Move the location then minecraft frrezzing and Crash, Here is The Crash log


      Minecraft has crashed!      
      ----------------------      

Minecraft has stopped running because it encountered a problem; Reading NBT data

A full error report has been saved to C:\Users\Admin\AppData\Roaming\.minecraft\crash-reports\crash-2015-08-04_20.50.24-client.txt - Please include a copy of that file (Not this screen!) if you report this crash to anyone; without it, they will not be able to help fix the crash :(



--- BEGIN ERROR REPORT 9567038e --------
Full report at:
C:\Users\Admin\AppData\Roaming\.minecraft\crash-reports\crash-2015-08-04_20.50.24-client.txt
Please show that file to Mojang, NOT just this screen!

Generated 15. 8. 4 오후 8:50

-- Corrupt NBT tag --
Details:
	Tag type found: STRING
	Tag type expected: SHORT
	Tag name: id
Stacktrace:
	at bs.d(SourceFile:116)
	at wm.c(SourceFile:123)
	at wm.a(SourceFile:70)
	at ng.a(SourceFile:1070)

-- Entity being loaded --
Details:
	Entity Type: Spider (sh)
	Entity ID: 271
	Entity Name: §aLv.1 §8어둠의 거미
	Entity's Exact location: 0.00, 0.00, 0.00
	Entity's Block location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at mp.f(SourceFile:1053)
	at zs.a(SourceFile:116)
	at zs.h(SourceFile:234)
	at biy.a(SourceFile:22)
	at biy.a(SourceFile:17)
	at biy.a(SourceFile:12)

-- Tile Entity Details --
Details:
	Name: MobSpawner // aqj
	Block type: ID #52 (tile.mobSpawner // ank)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-74,45,509), Chunk: (at 6,2,13 in -5,31; contains blocks -80,0,496 to -65,255,511), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #52 (tile.mobSpawner // ank)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at bjd.a(SourceFile:107)
	at bjd.a(SourceFile:99)
	at bfy.a(SourceFile:314)
	at bfq.a(SourceFile:894)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bdv['swan201'/410112, l='MpServer', x=-68.02, y=64.62, z=518.52]]
	Chunk stats: MultiplayerChunkCache: 70
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-132,65,248), Chunk: (at 12,4,8 in -9,15; contains blocks -144,0,240 to -129,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 241670023 game time, -27119985 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 20 total; [bdv['swan201'/410112, l='MpServer', x=-68.02, y=64.62, z=518.52], sh['§aLv.1 §8어둠의 거미'/410118, l='MpServer', x=-53.00, y=46.00, z=496.69], sm['주민'/410054, l='MpServer', x=-70.50, y=53.00, z=529.50], sh['§aLv.1 §8어둠의 거미'/410119, l='MpServer', x=-63.41, y=46.00, z=497.88], sf['§aLv.2 §7악령의 영혼'/410055, l='MpServer', x=-65.56, y=52.50, z=532.91], sj['§aLv.1 §7마이너 좀비'/410116, l='MpServer', x=-54.41, y=46.00, z=499.91], sh['§aLv.1 §8어둠의 거미'/410117, l='MpServer', x=-57.50, y=46.00, z=502.97], sh['§aLv.1 §8어둠의 거미'/410114, l='MpServer', x=-62.72, y=52.00, z=514.94], sj['§aLv.3 §7강인함의 좀비'/410115, l='MpServer', x=-56.56, y=49.00, z=525.69], sj['§aLv.3 §7강인함의 좀비'/410113, l='MpServer', x=-52.34, y=45.00, z=520.84], sh['§aLv.1 §8어둠의 거미'/410126, l='MpServer', x=-45.75, y=46.00, z=496.69], sj['§aLv.1 §7마이너 좀비'/410127, l='MpServer', x=-46.28, y=46.00, z=503.19], sj['§aLv.3 §7강인함의 좀비'/410124, l='MpServer', x=-42.94, y=45.00, z=517.47], sh['§aLv.1 §8어둠의 거미'/410125, l='MpServer', x=-43.72, y=46.00, z=496.69], sj['§aLv.3 §7강인함의 좀비'/410122, l='MpServer', x=-41.81, y=45.00, z=525.81], sj['§aLv.3 §7강인함의 좀비'/410123, l='MpServer', x=-43.81, y=45.00, z=520.06], sh['§aLv.1 §8어둠의 거미'/410120, l='MpServer', x=-49.03, y=46.00, z=509.28], sf['§aLv.2 §7악령의 영혼'/410056, l='MpServer', x=-68.19, y=48.00, z=537.88], sm['주민'/410057, l='MpServer', x=-71.50, y=53.00, z=519.50], sj['§aLv.3 §7강인함의 좀비'/410121, l='MpServer', x=-38.50, y=45.00, z=525.09]]
	Retry entities: 0 total; []
Stacktrace:
	at bds.a(SourceFile:282)
	at net.minecraft.client.Minecraft.b(SourceFile:1881)
	at net.minecraft.client.Minecraft.run(SourceFile:535)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.5.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 160557104 bytes (153 MB) / 252968960 bytes (241 MB) up to 1060372480 bytes (1011 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - Macro / Keybind Mod version 0.9.9
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 20727 (1160712 bytes; 1 MB) allocated, 2 (112 bytes; 0 MB) used
	Suspicious classes: StringCache, Key, Glyph, ...[com.mumfrey.liteloader.LiteMod, PreLoginListener, ChatRenderListener, ...], [com.mumfrey.liteloader.core.LiteLoader, LiteLoaderLogFormatter, HookPluginChannels, ...], [com.mumfrey.liteloader.gui.GuiControlsPaginated], [com.mumfrey.liteloader.util.ModUtilities, PrivateFields, StaticFields], [com.mumfrey.liteloader.util.log.ConsoleHandler], [net.eq2online.console.Log], [net.eq2online.jinput.JInputComponentRegistry], [net.eq2online.macros.LiteModMacros, AutoDiscoveryAgent, AutoDiscoveryState, ...], [net.eq2online.macros.compatibility.AbstractionLayer, DelegateDisconnect, GuiControl, ...], [net.eq2online.macros.compatibility.hooks.Packet22CollectHookable], [net.eq2online.macros.core.MacroModCore, Macros, MacroTemplate, ...], [net.eq2online.macros.core.params.Type], [net.eq2online.macros.event.MacroEventManager, MacroEventDispatcher, MacroEventValueWatcher, ...], [net.eq2online.macros.event.providers.OnJoinGameProvider, OnChatProvider, OnInventorySlotChangeProvider, ...], [net.eq2online.macros.gui.controls.GuiListBox, GuiListBoxIconic, GuiListBoxFilebound, ...], [net.eq2online.macros.gui.controls.specialised.GuiListBoxFile, GuiListBoxTexturePack, GuiListBoxPlaces, ...], [net.eq2online.macros.gui.designable.LayoutManager, DesignableGui, DesignableGuiLayout, ...], [net.eq2online.macros.gui.designable.editor.GuiDialogBoxControlProperties, GuiDialogBoxTextAreaProperties], [net.eq2online.macros.gui.dialogs.GuiDialogBoxFirstRunPrompt, GuiDialogBoxErrorList], [net.eq2online.macros.gui.helpers.ListProvider, HelperThumbnailImage, HelperUserSkinDownload], [net.eq2online.macros.gui.layout.LayoutPanel, LayoutPanelStandard, LayoutPanelKeys, ...], [net.eq2online.macros.gui.list.ListObjectGeneric, ListObjectEditable], [net.eq2online.macros.gui.screens.GuiScreenWithHeader, GuiEditThumbnails, GuiControlsEx, ...], [net.eq2online.macros.gui.shared.GuiScreenEx, GuiDialogBox, GuiControlEx], [net.eq2online.macros.input.IInputHandlerModule, InputHandler, KeyInjectionProxy, ...], [net.eq2online.macros.interfaces.ILocalisationProvider, ISettingsProvider, ISaveSettings, ...], [net.eq2online.macros.permissions.MacroModPermissions], [net.eq2online.macros.rendering.FontRendererLegacy, RenderEngineHelper], [net.eq2online.macros.scripting.IErrorLogger, IDocumentor, VariableProviderArray, ...], [net.eq2online.macros.scripting.actions.ScriptActionAchievementGet, ScriptActionBindGui, ScriptActionClearChat, ...], [net.eq2online.macros.scripting.actions.game.ScriptActionSlotClick, ScriptActionCraft, ScriptActionCraftAndWait, ...], [net.eq2online.macros.scripting.actions.input.ScriptActionKey, ScriptActionKeyUp, ScriptActionKeyDown, ...], [net.eq2online.macros.scripting.actions.lang.ScriptActionAssign, ScriptActionArraySize, ScriptActionBreak, ...], [net.eq2online.macros.scripting.actions.mod.ScriptActionConfig, ScriptActionImport, ScriptActionUnimport], [net.eq2online.macros.scripting.actions.option.ScriptActionBind, ScriptActionGamma, ScriptActionChatHeight, ...], [net.eq2online.macros.scripting.api.IScriptActionProvider, IMacroActionContext, IMacrosAPIModule, ...], [net.eq2online.macros.scripting.crafting.IAutoCraftingInitiator, AutoCraftingManager], [net.eq2online.macros.scripting.exceptions.ScriptException], [net.eq2online.macros.scripting.iterators.ScriptedIteratorEnchantments, ScriptedIteratorPlayers, ScriptedIteratorEffects], [net.eq2online.macros.struct.ItemStackInfo, Place], [net.eq2online.obfuscation.ObfuscationMapping], [net.eq2online.permissions.PermissionsManagerBootstrap, PermissionsEventListener, PermissionsManager, ...], [net.eq2online.permissions.impl.PermissionsManagerClient, LocalPermissions], [net.eq2online.util.Colour], [net.eq2online.xml.Xmlns, Xml, PropertiesXMLUtils, ...], [net.java.games.input.ControllerEnvironment, DirectAndRawInputEnvironmentPlugin, DefaultControllerEnvironment, ...], [net.java.games.util.plugins.Plugins, Plugin]
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	LWJGL: 2.9.0
	OpenGL: AMD Radeon R9 200 Series GL version 4.4.13292 Compatibility Profile Context 14.502.1014.1001, ATI Technologies Inc.
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Texture Pack: Default
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 500 (28000 bytes; 0 MB) allocated, 33 (1848 bytes; 0 MB) used

java.lang.ClassCastException: ce cannot be cast to cd
	at bs.d(SourceFile:116)
	at wm.c(SourceFile:123)
	at wm.a(SourceFile:70)
	at ng.a(SourceFile:1070)
	at mp.f(SourceFile:1053)
	at zs.a(SourceFile:116)
	at zs.h(SourceFile:234)
	at biy.a(SourceFile:22)
	at biy.a(SourceFile:17)
	at biy.a(SourceFile:12)
	at bjd.a(SourceFile:107)
	at bjd.a(SourceFile:99)
	at bfy.a(SourceFile:314)
	at bfq.a(SourceFile:894)
	at bfq.b(SourceFile:745)
	at net.minecraft.client.Minecraft.K(SourceFile:597)
	at net.minecraft.client.Minecraft.run(SourceFile:526)
	at java.lang.Thread.run(Thread.java:745)
--- END ERROR REPORT 9269601c ----------

**Comment by Shevchik** [comment]
That shit again, i should probably just remove spawners nbt data sending.

**Comment by swan201** [comment]
I remove that location spawner. but still crash.

**Comment by Shevchik** [comment]
There should be a new crash report then. But probably you have a lot of spawners with custom nbt tags attached to it.

**Comment by swan201** [comment]
I need to del All Coustom nbt tags Spawners?

**Comment by Shevchik** [comment]
Or wait until i fix it

**Comment by swan201** [comment]
Ok I waitng for fix it. Plz Notication to me if that bug fix it

**Comment by Shevchik** [comment]
Try now
