### ISSUE TITLE
1.5.2 /1.6.X cant read Plugins kick message.

### ISSUE THREAD

**Issue by swan201** [Shevchik/ProtocolSupport#47]
I Use AAC Spigot Plugins. 

1.5.2 And 1.6.X User is Suddenly kick to End of Stream.  console only Show Netty error. I disable AAC. User are not kick. I think 1.5.2 and 1.6.X Client are not decorde the some kick mesage. 

[20:35:47 WARN]: io.netty.handler.codec.DecoderException: NettyChannelInjector.d
ecode() did not read anything but decoded a message.
[20:35:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecod
e(ByteToMessageDecoder.java:268)
[20:35:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRe
ad(ByteToMessageDecoder.java:149)
[20:35:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invoke
ChannelRead(AbstractChannelHandlerContext.java:333)
[20:35:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireCh
annelRead(AbstractChannelHandlerContext.java:319)
[20:35:47 WARN]:        at com.comphenix.protocol.compat.netty.independent.Netty
ChannelInjector$4.channelRead(NettyChannelInjector.java:280)
[20:35:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invoke
ChannelRead(AbstractChannelHandlerContext.java:333)
[20:35:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireCh
annelRead(AbstractChannelHandlerContext.java:319)
[20:35:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRe
ad(ByteToMessageDecoder.java:163)
[20:35:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invoke
ChannelRead(AbstractChannelHandlerContext.java:333)
[20:35:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireCh
annelRead(AbstractChannelHandlerContext.java:319)
[20:35:47 WARN]:        at io.netty.handler.timeout.ReadTimeoutHandler.channelRe
ad(ReadTimeoutHandler.java:150)
[20:35:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invoke
ChannelRead(AbstractChannelHandlerContext.java:333)
[20:35:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireCh
annelRead(AbstractChannelHandlerContext.java:319)
[20:35:47 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRe
ad(DefaultChannelPipeline.java:787)
[20:35:47 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUn
safe.read(AbstractNioByteChannel.java:130)
[20:35:47 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(
NioEventLoop.java:511)
[20:35:47 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys
Optimized(NioEventLoop.java:468)
[20:35:47 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys
(NioEventLoop.java:382)
[20:35:47 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.ja
va:354)
[20:35:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.
run(SingleThreadEventExecutor.java:116)
[20:35:47 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:35:47 INFO]: EntryPoint lost connection: Internal Exception: io.netty.handle
r.codec.DecoderException: NettyChannelInjector.decode() did not read anything bu
t decoded a message.
[20:35:47 INFO]: <-- [-] EntryPoint

**Comment by Shevchik** [comment]
AAC is not opensource, so i can't help with it. You better ask it's author.

**Comment by swan201** [comment]
But That Problem is Protocolsupport side error


[00:06:42] [Netty Server IO #3/WARN]: Caused by: java.io.IOException: Can't deserialize unknown packet 103
[00:06:42] [Netty Server IO #3/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.serverboundtransformer.PacketDecoder.decode(PacketDecoder.java:56)
[00:06:42] [Netty Server IO #3/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedDecoder.decode(WrappedDecoder.java:27)
[00:06:42] [Netty Server IO #3/WARN]: 	at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
[00:06:42] [Netty Server IO #3/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:06:42] [Netty Server IO #3/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[00:06:42] [Netty Server IO #3/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[00:06:42] [Netty Server IO #3/WARN]: 	... 21 more

**Comment by Shevchik** [comment]
That this needs reporuducing. I can't fix error if i don't know where it is. Also that's not a full log.

**Comment by swan201** [comment]
i Wlll hope this log is help the debug.

http://pastebin.com/P2yTmC5u

**Comment by Shevchik** [comment]
Okay, probably some plugin tries to use netty pipeline and makes decoder receive a packet buffer. But that won't work because data format is different for 1.5.2 and 1.6.4. All you can do is to find this plugin and try to rewrite it.

**Comment by swan201** [comment]
So It this Bug can fix Protocolsupport Side? or Need to rewrite all that Plugins?

**Comment by Shevchik** [comment]
Yep, that can't be fixed on protocolsupport side.
