### ISSUE TITLE
Can't Log in to server if don't have hostname

### ISSUE THREAD

**Issue by Castar** [Shevchik/ProtocolSupport#48]
im using #195 build.
most korea ip is don't have hostname.
and it makes can't connect to server
please fix Thanks!

it is error:
[21:27:11 INFO]: /119.149.12.244:55302 lost connection: Internal Exception: java.lang.NoSuchFieldError: hostname
[21:27:11 INFO]: /127.0.0.1:50982 lost connection: Internal Exception: java.lang.NoSuchFieldError: hostname
[21:27:11 INFO]: /127.0.0.1:50983 lost connection: Internal Exception: java.lang.NoSuchFieldError: hostname
[21:27:11 INFO]: /39.127.241.166:50985 lost connection: Internal Exception: java.lang.NoSuchFieldError: hostname

and its debug mode log:
[23:18:56 INFO]: Enabled debug
[23:19:10 WARN]: java.lang.NoSuchFieldError: hostname
[23:19:10 WARN]:        at protocolsupport.protocol.transformer.AbstractHandshakeListener.a(AbstractHandshakeListener.java:81)
[23:19:10 WARN]:        at net.minecraft.server.v1_8_R3.PacketHandshakingInSetProtocol.a(PacketHandshakingInSetProtocol.java:29)
[23:19:10 WARN]:        at net.minecraft.server.v1_8_R3.PacketHandshakingInSetProtocol.a(PacketHandshakingInSetProtocol.java:1)
[23:19:10 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:124)
[23:19:10 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:325)
[23:19:10 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:1)
[23:19:10 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:19:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:19:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:19:10 WARN]:        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:280)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:19:10 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:19:10 WARN]:        at protocolsupport.protocol.core.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:108)
[23:19:10 WARN]:        at protocolsupport.protocol.core.initial.InitialPacketDecoder.channelRead(InitialPacketDecoder.java:90)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:19:10 WARN]:        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[23:19:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[23:19:10 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[23:19:10 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
[23:19:10 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
[23:19:10 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
[23:19:10 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
[23:19:10 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
[23:19:10 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[23:19:10 WARN]:        at java.lang.Thread.run(Unknown Source)
[23:19:11 INFO]: /127.0.0.1:51559 lost connection: Internal Exception: java.lang.NoSuchFieldError: hostname

**Comment by Shevchik** [comment]
YOu server is outdated, you need the latest spigot 1.8.8 build.

It has nothing to do with naving ip hostname.

**Comment by Castar** [comment]
thanks for quickly answer!
but im using spigot 1.8.8...

**Comment by Castar** [comment]
thanks! resolved. im using outdated spigot 1.8.8 build
