### ISSUE TITLE
Client crash caused by scoreboard.

### ISSUE THREAD

**Issue by DNx5** [Shevchik/ProtocolSupport#50]
the client will crash everytime they join with 1.7.10
i'm using latest spigot and latest protocolsupport (Dev build)
Here is the log:
```
java.lang.NullPointerException: Unexpected error
at net.minecraft.scoreboard.Scoreboard.func_96519_k(SourceFile:129)
at net.minecraft.client.network.NetHandlerPlayClient.func_147291_a(NetHandlerPlayClient.java:1489)
at net.minecraft.network.play.server.S3BPacketScoreboardObjective.func_148833_a(SourceFile:43)
at net.minecraft.network.play.server.S3BPacketScoreboardObjective.func_148833_a(SourceFile:9)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Shevchik** [comment]
Server tried to remove objective that doesn't exist. Check your plugins, one of them operates with scoreboards improperly.

**Comment by DNx5** [comment]
one of my plugin using dummy scoreboard to display player stats.
I will check that, thank you
