### ISSUE TITLE
1.5.2 Client Connection Problem to Bungee Connected Server

### ISSUE THREAD

**Issue by swan201** [Shevchik/ProtocolSupport#56]
I user Lastest Bungeecord and ProtocolsupportBungee And ProtocolSupport And Today Spigot Build.

1.7.X and 1.8.X Clinet is all Fine. but 1.5.2 client have problem to connect bungee connected Server.

1.5.2 client connect to lobby server is fine. but if 1.5.2 client try to connect bungee connected server crash

Internal exception: Java.io.IOException: Bad compressed data format

I Think lasteset bungeecord use Compress system. i use ps debug. but bukkit is not any log. and bungeecord have too many ps debug log. sorry to i cant catch any log

**Comment by swan201** [comment]
finally i catch log to bungeecord

00:13:53 [정보] [swan201] <-> InitialHandler has connected
00:13:55 [정보] [swan201] <-> ServerConnector [Lobby] has connected
00:14:14 [정보] [swan201] <-> ServerConnector [Wild] has connected
00:14:14 [심각] [swan201] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:944)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:239)
	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:49)
	at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:138)
	at net.md_5.bungee.tab.ServerUnique.onServerChange(ServerUnique.java:77)
	at protocolsupport.protocol.transformer.v_1_5_v1_6_shared.handlers.ServerConnectHandler.handle(ServerConnectHandler.java:162)
	at net.md_5.bungee.protocol.packet.Login.handle(Login.java:60)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:76)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at protocolsupport.utils.Utils.clampString(Utils.java:10)
	at protocolsupport.protocol.transformer.v_1_5_v1_6_shared.packets.PlayerListItemPacket.write(PlayerListItemPacket.java:45)
	at protocolsupport.protocol.transformer.v_1_5_v1_6_shared.PacketEncoder.encodePackets(PacketEncoder.java:43)
	at protocolsupport.protocol.transformer.v_1_5_v1_6_shared.PacketEncoder.encode(PacketEncoder.java:33)
	at protocolsupport.protocol.transformer.v_1_5_v1_6_shared.PacketEncoder.encode(PacketEncoder.java:14)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 27 more
00:14:14 [정보] [swan201] disconnected with: §fEncoderException : java.lang.NullPointerException @ io.netty.handler.codec.MessageToByteEncoder:125
00:14:14 [정보] [swan201] -> UpstreamBridge has disconnected
00:14:15 [정보] [swan201] <-> DownstreamBridge <-> [Lobby] has disconnected
00:14:15 [정보] [swan201] disconnected with: §f[Proxy] Lost connection to server.
00:14:15 [정보] [swan201] <-> DownstreamBridge <-> [Wild] has disconnected

**Comment by swan201** [comment]
moving to Protocolsupportbungee Issue
