### ISSUE TITLE
1.5.2 and 1.6.X Client kick some Server

### ISSUE THREAD

**Issue by swan201** [Shevchik/ProtocolSupport#58]
Here is the PS debug log. I use lastest bungeecord and bukkit and Protocolsupport suite.

Link this issue https://github.com/Shevchik/ProtocolSupportBungee/issues/6

[16:34:54] [Netty Server IO #0/WARN]: java.lang.ArrayIndexOutOfBoundsException: -126
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.typeremapper.id.RemappingTable.getRemap(RemappingTable.java:18)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:839)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PacketEncoder.encode(PacketEncoder.java:47)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:30)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:13)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:506)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:264)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:270)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[16:34:54] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6$3.run(NettyChannelInjector.java:361)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:34:54] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:34:54] [Netty Server IO #0/ERROR]: java.lang.ArrayIndexOutOfBoundsException: -126
[16:34:54] [Netty Server IO #0/WARN]: java.lang.ArrayIndexOutOfBoundsException: -126
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.typeremapper.id.RemappingTable.getRemap(RemappingTable.java:18)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:839)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PacketEncoder.encode(PacketEncoder.java:47)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:30)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:13)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:506)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:264)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:270)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[16:34:54] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6$3.run(NettyChannelInjector.java:361)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:34:54] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:34:54] [Netty Server IO #0/ERROR]: java.lang.ArrayIndexOutOfBoundsException: -126
[16:34:54] [Netty Server IO #0/WARN]: java.lang.ArrayIndexOutOfBoundsException: -126
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.typeremapper.id.RemappingTable.getRemap(RemappingTable.java:18)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:839)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PacketEncoder.encode(PacketEncoder.java:47)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:30)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:13)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:506)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:264)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:270)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[16:34:54] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6$3.run(NettyChannelInjector.java:361)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:34:54] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:34:54] [Netty Server IO #0/ERROR]: java.lang.ArrayIndexOutOfBoundsException: -126
[16:34:54] [Netty Server IO #0/WARN]: java.lang.ArrayIndexOutOfBoundsException: -126
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.typeremapper.id.RemappingTable.getRemap(RemappingTable.java:18)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:839)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PacketEncoder.encode(PacketEncoder.java:47)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:30)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:13)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:506)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:264)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:270)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[16:34:54] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6$3.run(NettyChannelInjector.java:361)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:34:54] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:34:54] [Netty Server IO #0/ERROR]: java.lang.ArrayIndexOutOfBoundsException: -126
[16:34:54] [Netty Server IO #0/WARN]: java.lang.ArrayIndexOutOfBoundsException: -126
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.typeremapper.id.RemappingTable.getRemap(RemappingTable.java:18)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:839)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PacketEncoder.encode(PacketEncoder.java:47)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:30)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:13)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:506)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:264)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:270)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[16:34:54] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6$3.run(NettyChannelInjector.java:361)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:34:54] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:34:54] [Netty Server IO #0/ERROR]: java.lang.ArrayIndexOutOfBoundsException: -126
[16:34:54] [Netty Server IO #0/WARN]: java.lang.ArrayIndexOutOfBoundsException: -126
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.typeremapper.id.RemappingTable.getRemap(RemappingTable.java:18)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PlayPacketTransformer.tranform(PlayPacketTransformer.java:839)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.transformer.v_1_5.clientboundtransformer.PacketEncoder.encode(PacketEncoder.java:47)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:30)
[16:34:54] [Netty Server IO #0/WARN]: 	at protocolsupport.protocol.core.wrapped.WrappedEncoder.encode(WrappedEncoder.java:13)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:506)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:264)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:270)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[16:34:54] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6$3.run(NettyChannelInjector.java:361)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:34:54] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:34:54] [Netty Server IO #0/ERROR]: java.lang.ArrayIndexOutOfBoundsException: -126
[16:34:54] [Netty Server IO #0/WARN]: java.io.IOException: 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.nio.ch.SocketDispatcher.write0(Native Method)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.nio.ch.SocketDispatcher.write(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.nio.ch.IOUtil.write(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at sun.nio.ch.SocketChannelImpl.write(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:270)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:315)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:676)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1059)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:669)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:688)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:718)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327)
[16:34:54] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[16:34:54] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6$3.run(NettyChannelInjector.java:361)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[16:34:54] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:34:54] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:34:54] [Netty Server IO #0/WARN]: java.nio.channels.ClosedChannelException
[16:34:54] [Netty Server IO #0/WARN]: java.nio.channels.ClosedChannelException
[16:34:54] [Netty Server IO #0/WARN]: java.nio.channels.ClosedChannelException
[16:34:54] [Netty Server IO #0/WARN]: java.nio.channels.ClosedChannelException
[16:34:54] [Netty Server IO #0/WARN]: java.nio.channels.ClosedChannelException
[16:34:54] [Netty Server IO #0/WARN]: java.nio.channels.ClosedChannelException
[16:34:54] [Netty Server IO #0/WARN]: java.nio.channels.ClosedChannelException
[16:34:54] [Netty Server IO #0/WARN]: java.nio.channels.ClosedChannelException
[16:34:54] [Netty Server IO #0/WARN]: java.nio.channels.ClosedChannelException
[16:34:54] [Server thread/INFO]: swan201 lost connection: Internal Exception: java.io.IOException: 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by swan201** [comment]
Yes, Thank you!
