### ISSUE TITLE
1.8.8 error on startup

### ISSUE THREAD

**Issue by CryMC** [Shevchik/ProtocolSupport#59]
[12:40:53 INFO]: [ProtocolSupport] Loading ProtocolSupport v4.19
[12:40:53 WARN]: java.lang.IllegalAccessException: Class protocolsupport.injector.NettyInjector can not access a member of class io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor with modifiers "private final"
[12:40:53 WARN]: 	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
[12:40:53 WARN]: 	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
[12:40:53 WARN]: 	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
[12:40:53 WARN]: 	at java.lang.reflect.Field.set(Field.java:761)
[12:40:53 WARN]: 	at protocolsupport.injector.NettyInjector.inject(NettyInjector.java:22)
[12:40:53 WARN]: 	at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:18)
[12:40:53 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297)
[12:40:53 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203)
[12:40:53 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[12:40:53 WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by Shevchik** [comment]
This error is not possible, something is wrong with your java.

**Comment by CryMC** [comment]
I can't reproduce it, odd.
