### ISSUE TITLE
io.netty.handler.codec.CorruptedFrameException

### ISSUE THREAD

**Issue by LemADEC** [Shevchik/ProtocolSupport#66]
Plugin is sending empty packets with latest version, Bungee reject those with the following exception
```
io.netty.handler.codec.CorruptedFrameException: Empty Packet!
    at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:34)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
```

It's reproduced while removing all other plugins on both Bungee and Spigot (only ProtocolSupport build 212 on Spigot is installed).
In spigot server, use-native-transport value doesn't affect the result.
In spigot server, late-bind is set to false.

Connecting with a Vanilla 1.8.7 client works.
Connecting with a Vanilla 1.7.10 or Forge 1.7.10 client reproduces the issue.

**Comment by LemADEC** [comment]
This is with latest BungeeCord (build1088) and latest Spigot (just recompiled it).

**Comment by Shevchik** [comment]
Not a ProtocolSupport issue

**Comment by LemADEC** [comment]
Can you be more specific on what's causing this issue?

**Comment by Shevchik** [comment]
BungeeCord itself. It doesn't allow empty packets which 1.7.* client sends sometimes.

**Comment by LemADEC** [comment]
A 1.7.10 server won't cause such error when 1.7.10 client connect, so it seems more likely that the plugin is pushing empty packets
