### ISSUE TITLE
Skull Heads causes a crash/causes a bug on the graphic renderer due to "Invalid NBT tag" (SkullOwner) [1.5.2/1.6.X]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Shevchik/ProtocolSupport#68]
```

      Minecraft has crashed!      
      ----------------------      

Minecraft has stopped running because it encountered a problem; Reading NBT data

A full error report has been saved to C:\Users\Leonardo\AppData\Roaming\.minecraft\crash-reports\crash-2015-10-18_14.03.38-client.txt - Please include a copy of that file (Not this screen!) if you report this crash to anyone; without it, they will not be able to help fix the crash :(



--- BEGIN ERROR REPORT 23ca78a5 --------
Full report at:
C:\Users\Leonardo\AppData\Roaming\.minecraft\crash-reports\crash-2015-10-18_14.03.38-client.txt
Please show that file to Mojang, NOT just this screen!

Generated 18/10/15 14:03

-- Corrupt NBT tag --
Details:
	Tag type found: COMPOUND
	Tag type expected: STRING
	Tag name: SkullOwner
Stacktrace:
	at bs.i(SourceFile:161)
	at xi.l(SourceFile:118)
	at wm.s(SourceFile:357)
	at wm.a(SourceFile:385)
	at ayl.a(SourceFile:191)
	at ayl.a(SourceFile:171)

-- Screen render details --
Details:
	Screen name: ayv
	Mouse location: Scaled: (272, 91). Absolute: (544, 522)
	Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bdv['MrPowerGamerBR'/11712, l='MpServer', x=29,43, y=66,62, z=-8,54]]
	Chunk stats: MultiplayerChunkCache: 50
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,66,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 725898 game time, 888168 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 72 total; [bdv['MrPowerGamerBR'/11712, l='MpServer', x=29,43, y=66,62, z=-8,54], nf['entity.ItemFrame.name'/11776, l='MpServer', x=16,94, y=65,50, z=-1,50], nf['entity.ItemFrame.name'/11777, l='MpServer', x=20,06, y=65,50, z=-1,50], nf['entity.ItemFrame.name'/11778, l='MpServer', x=22,94, y=65,50, z=-1,50], nf['entity.ItemFrame.name'/11779, l='MpServer', x=26,06, y=65,50, z=-1,50], nf['entity.ItemFrame.name'/11780, l='MpServer', x=28,50, y=65,50, z=-3,94], nf['entity.ItemFrame.name'/11781, l='MpServer', x=28,50, y=65,50, z=-7,06], nf['entity.ItemFrame.name'/11782, l='MpServer', x=28,50, y=65,50, z=-9,94], nf['entity.ItemFrame.name'/11783, l='MpServer', x=28,50, y=65,50, z=-13,06], nf['entity.ItemFrame.name'/11784, l='MpServer', x=28,50, y=65,50, z=-15,94], nf['entity.ItemFrame.name'/11790, l='MpServer', x=28,50, y=65,50, z=22,94], nf['entity.ItemFrame.name'/11791, l='MpServer', x=28,50, y=65,50, z=20,06], nf['entity.ItemFrame.name'/11792, l='MpServer', x=28,50, y=65,50, z=16,94], nf['entity.ItemFrame.name'/11800, l='MpServer', x=14,06, y=65,50, z=-27,50], nf['entity.ItemFrame.name'/11801, l='MpServer', x=10,94, y=65,50, z=-27,50], nf['entity.ItemFrame.name'/11802, l='MpServer', x=8,06, y=65,50, z=-27,50], nf['entity.ItemFrame.name'/11803, l='MpServer', x=4,94, y=65,50, z=-27,50], nf['entity.ItemFrame.name'/11804, l='MpServer', x=2,50, y=65,50, z=-25,06], nf['entity.ItemFrame.name'/11805, l='MpServer', x=2,50, y=65,50, z=-21,94], nf['entity.ItemFrame.name'/11806, l='MpServer', x=2,50, y=65,50, z=-19,06], nf['entity.ItemFrame.name'/11822, l='MpServer', x=-1,50, y=65,50, z=-19,06], nf['entity.ItemFrame.name'/11823, l='MpServer', x=-1,50, y=65,50, z=-21,94], nf['entity.ItemFrame.name'/11824, l='MpServer', x=-1,50, y=65,50, z=-25,06], bfk['Unknown'/11764, l='MpServer', x=-8,47, y=-38377,41, z=16,59], nf['entity.ItemFrame.name'/11830, l='MpServer', x=28,50, y=65,50, z=-19,06], nf['entity.ItemFrame.name'/11831, l='MpServer', x=28,50, y=65,50, z=-21,94], nf['entity.ItemFrame.name'/11832, l='MpServer', x=28,50, y=65,50, z=-25,06], nf['entity.ItemFrame.name'/11833, l='MpServer', x=26,06, y=65,50, z=-27,50], nf['entity.ItemFrame.name'/11834, l='MpServer', x=22,94, y=65,50, z=-27,50], nf['entity.ItemFrame.name'/11835, l='MpServer', x=20,06, y=65,50, z=-27,50], nf['entity.ItemFrame.name'/11836, l='MpServer', x=16,94, y=65,50, z=-27,50], bfk['_Poker_Face_'/11764, l='MpServer', x=-8,47, y=-38456,64, z=16,59], nf['entity.ItemFrame.name'/11713, l='MpServer', x=2,50, y=65,50, z=4,94], nf['entity.ItemFrame.name'/11714, l='MpServer', x=2,50, y=65,50, z=8,06], nf['entity.ItemFrame.name'/11715, l='MpServer', x=2,50, y=65,50, z=10,94], nf['entity.ItemFrame.name'/11716, l='MpServer', x=2,50, y=65,50, z=14,06], nf['entity.ItemFrame.name'/11717, l='MpServer', x=14,06, y=65,50, z=2,50], nf['entity.ItemFrame.name'/11718, l='MpServer', x=10,94, y=65,50, z=2,50], nf['entity.ItemFrame.name'/11719, l='MpServer', x=8,06, y=65,50, z=2,50], nf['entity.ItemFrame.name'/11720, l='MpServer', x=4,94, y=65,50, z=2,50], nf['entity.ItemFrame.name'/11721, l='MpServer', x=-1,50, y=65,50, z=4,94], nf['entity.ItemFrame.name'/11722, l='MpServer', x=-1,50, y=65,50, z=10,94], nf['entity.ItemFrame.name'/11723, l='MpServer', x=-1,50, y=65,50, z=8,06], nf['entity.ItemFrame.name'/11724, l='MpServer', x=-1,50, y=65,50, z=14,06], nf['entity.ItemFrame.name'/11730, l='MpServer', x=4,94, y=65,50, z=-1,50], nf['entity.ItemFrame.name'/11731, l='MpServer', x=8,06, y=65,50, z=-1,50], nf['entity.ItemFrame.name'/11732, l='MpServer', x=10,94, y=65,50, z=-1,50], nf['entity.ItemFrame.name'/11733, l='MpServer', x=14,06, y=65,50, z=-1,50], nf['entity.ItemFrame.name'/11734, l='MpServer', x=2,50, y=65,50, z=-15,94], nf['entity.ItemFrame.name'/11735, l='MpServer', x=2,50, y=65,50, z=-13,06], nf['entity.ItemFrame.name'/11736, l='MpServer', x=2,50, y=65,50, z=-9,94], nf['entity.ItemFrame.name'/11737, l='MpServer', x=2,50, y=65,50, z=-7,06], nf['entity.ItemFrame.name'/11738, l='MpServer', x=2,50, y=65,50, z=-3,94], nf['entity.ItemFrame.name'/11739, l='MpServer', x=28,50, y=65,50, z=14,06], nf['entity.ItemFrame.name'/11740, l='MpServer', x=28,50, y=65,50, z=10,94], nf['entity.ItemFrame.name'/11741, l='MpServer', x=28,50, y=65,50, z=8,06], nf['entity.ItemFrame.name'/11742, l='MpServer', x=28,50, y=65,50, z=4,94], nf['entity.ItemFrame.name'/11743, l='MpServer', x=26,06, y=65,50, z=2,50], nf['entity.ItemFrame.name'/11744, l='MpServer', x=22,94, y=65,50, z=2,50], nf['entity.ItemFrame.name'/11745, l='MpServer', x=20,06, y=65,50, z=2,50], nf['entity.ItemFrame.name'/11746, l='MpServer', x=16,94, y=65,50, z=2,50], nf['entity.ItemFrame.name'/11747, l='MpServer', x=2,50, y=65,50, z=16,94], nf['entity.ItemFrame.name'/11748, l='MpServer', x=2,50, y=65,50, z=20,06], nf['entity.ItemFrame.name'/11750, l='MpServer', x=2,50, y=65,50, z=22,94], nf['entity.ItemFrame.name'/11755, l='MpServer', x=-1,50, y=65,50, z=16,94], nf['entity.ItemFrame.name'/11756, l='MpServer', x=-1,50, y=65,50, z=20,06], nf['entity.ItemFrame.name'/11757, l='MpServer', x=-1,50, y=65,50, z=22,94], nf['entity.ItemFrame.name'/11766, l='MpServer', x=-1,50, y=65,50, z=-3,94], nf['entity.ItemFrame.name'/11767, l='MpServer', x=-1,50, y=65,50, z=-7,06], nf['entity.ItemFrame.name'/11768, l='MpServer', x=-1,50, y=65,50, z=-9,94], nf['entity.ItemFrame.name'/11769, l='MpServer', x=-1,50, y=65,50, z=-13,06], nf['entity.ItemFrame.name'/11770, l='MpServer', x=-1,50, y=65,50, z=-15,94]]
	Retry entities: 0 total; []
Stacktrace:
	at bds.a(SourceFile:282)
	at net.minecraft.client.Minecraft.b(SourceFile:1881)
	at net.minecraft.client.Minecraft.run(SourceFile:535)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.5.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 113968496 bytes (108 MB) / 182673408 bytes (174 MB) up to 255066112 bytes (243 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 8761 (490616 bytes; 0 MB) allocated, 51 (2856 bytes; 0 MB) used
	Suspicious classes: No suspicious classes found.
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	LWJGL: 2.9.0
	OpenGL: Mobile Intel(R) 4 Series Express Chipset Family GL version 2.1.0 - Build 8.15.10.1994, Intel
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Texture Pack: Default
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 329 (18424 bytes; 0 MB) allocated, 88 (4928 bytes; 0 MB) used

java.lang.ClassCastException: bs cannot be cast to ce
	at bs.i(SourceFile:161)
	at xi.l(SourceFile:118)
	at wm.s(SourceFile:357)
	at wm.a(SourceFile:385)
	at ayl.a(SourceFile:191)
	at ayl.a(SourceFile:171)
	at bfq.b(SourceFile:768)
	at net.minecraft.client.Minecraft.K(SourceFile:597)
	at net.minecraft.client.Minecraft.run(SourceFile:526)
	at java.lang.Thread.run(Unknown Source)
--- END ERROR REPORT 65cb2b99 ----------
```

This errors happens when you click on a Skull with a custom Owner (Example: Spawn a Skull Head with Essentials "/skull MrPowerGamerBR" then just click on the skull), this will cause a crash.

Maybe the 1.8.8 Skull NBT needs to be converted to a 1.5.2 Skull NBT?

**UPDATE:**
This bug also causes the Minecraft graphic render to bug everything out (as noticed in the #67 issue)
![2015-10-19_16 46 21](https://cloud.githubusercontent.com/assets/9496359/10587696/104fd7e4-7681-11e5-9c98-f787127b94e3.png)
![2015-10-19_16 46 43](https://cloud.githubusercontent.com/assets/9496359/10587697/1055e094-7681-11e5-9889-3eabb7bc17cd.png)

Launcher log:
```
u: Reading NBT data
	at bs.i(SourceFile:163)
	at bht.a(SourceFile:163)
	at bht.c(SourceFile:23)
	at bho.a(SourceFile:134)
	at bht.a(SourceFile:130)
	at bht.a(SourceFile:23)
	at bgy.a(SourceFile:201)
	at bgy.a(SourceFile:181)
	at bfy.a(SourceFile:307)
	at bfq.a(SourceFile:894)
	at bfq.b(SourceFile:745)
	at net.minecraft.client.Minecraft.K(SourceFile:597)
	at net.minecraft.client.Minecraft.run(SourceFile:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: bs cannot be cast to ce
	at bs.i(SourceFile:161)
	... 13 more
``` 

**UPDATE 2:**
Also happens in 1.6.X

**Comment by MrPowerGamerBR** [comment]
Also affects 1.5.2 and 1.6.X.

This issue doesn't affect 1.7.2 and versions above it.

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by MrPowerGamerBR** [comment]
Fixed in the latest Dev build! :smile: 

Will wait @swan201 to report if the issue was fixed here (because, oh well, I only could reproduce the render bug in his server), if he doesn't respond, then I will close the issue.

**Comment by swan201** [comment]
ok, All in fine. I'm Hosting almost 40 Minecraft Server to user protocolsupport. So I can find rare bug to easy haha... (too hard to all bug report ;.;)

**Comment by MrPowerGamerBR** [comment]
Can confirm, no more "funky upside down" entities on @swan201's Server :+1: 

Closing this issue, fixed in the latest dev build.
